debug: 0
device: 'MPD218'
triggers:
    # bank A, row 1 pads - vim MOVEMENT
  - event: 'Note on'
    data: '^note 36, velocity \d+$'
    text: '0' # head of line
  - event: 'Note on'
    data: '^note 37, velocity \d+$'
    text: '^' # first non-blank char of line
  - event: 'Note on'
    data: '^note 38, velocity \d+$'
    text: 'g_' # last non-blank char of line
  - event: 'Note on'
    data: '^note 39, velocity \d+$'
    text: '$' # end of line
    # bank A, row 2 pads - vim BITS
  - event: 'Note on'
    data: '^note 40, velocity \d+$'
    text: ' ;ul' # use lib ... sandbox ...
  - event: 'Note on'
    data: '^note 41, velocity \d+$'
    text: ' ;iv' # my $x = shift ...
  - event: 'Note on'
    data: '^note 42, velocity \d+$'
    text: ' ;my' # add my to beginning of line
  - event: 'Note on'
    data: '^note 43, velocity \d+$'
    text: ' ;dt' # add done_testing();exit
    # bank A, row 3 pads - vim git things
  - event: 'Note on'
    data: '^note 44, velocity \d+$'
    text: ':GitGutterPrevHunk' # previous hunk
  - event: 'Note on'
    data: '^note 45, velocity \d+$'
    text: ':GitGutterToggle' # toggle gitgutter
  - event: 'Note on'
    data: '^note 46, velocity \d+$'
    text: ':!git blame %'
  - event: 'Note on'
    data: '^note 47, velocity \d+$'
    text: ':GitGutterNextHunk' # next hunk
    # bank A, row 4 pads - vim TABS
  - event: 'Note on'
    data: '^note 48, velocity \d+$'
    text: 'gT' # go to the previous tab
  - event: 'Note on'
    data: '^note 49, velocity \d+$'
    text: ':tabnew' # open a new tab
  - event: 'Note on'
    data: '^note 50, velocity \d+$'
    text: ':Explore .' # open a new file
  - event: 'Note on'
    data: '^note 51, velocity \d+$'
    text: 'gt' # go to the next tab

    # bank B, row 1 pads - Firefox
  - event: 'Note on'
    data: '^note 52, velocity \d+$'
    key: 'alt+1' # 
  - event: 'Note on'
    data: '^note 53, velocity \d+$'
    key: 'alt+2' # 
  - event: 'Note on'
    data: '^note 54, velocity \d+$'
    key: 'alt+3' # 
  - event: 'Note on'
    data: '^note 55, velocity \d+$'
    key: 'alt+4' # 
    # bank B, row 2 pads - Firefox
  - event: 'Note on'
    data: '^note 56, velocity \d+$'
    key: 'alt+5' # 
  - event: 'Note on'
    data: '^note 57, velocity \d+$'
    key: 'alt+6' # 
  - event: 'Note on'
    data: '^note 58, velocity \d+$'
    key: 'alt+7' # 
  - event: 'Note on'
    data: '^note 59, velocity \d+$'
    key: 'alt+8' # 
    # bank B, row 3 pads - Firefox
  - event: 'Note on'
    data: '^note 60, velocity \d+$'
    key: 'alt+9' # 
  - event: 'Note on'
    data: '^note 61, velocity \d+$'
    key: 'ctrl+t' # new tab
  - event: 'Note on'
    data: '^note 62, velocity \d+$'
    key: 'shift+ctrl+t' # reopen tab
  - event: 'Note on'
    data: '^note 63, velocity \d+$'
    key: 'ctrl+r' # reload
    # bank B, row 4 pads - Firefox
  - event: 'Note on'
    data: '^note 64, velocity \d+$'
    key: 'ctrl+b' # bookmarks
  - event: 'Note on'
    data: '^note 65, velocity \d+$'
    key: 'ctrl+l' # address bar
  - event: 'Note on'
    data: '^note 66, velocity \d+$'
    key: 'ctrl+k' # search bar
  - event: 'Note on'
    data: '^note 67, velocity \d+$'
    key: 'ctrl+h' # history

    # bank A controllers - vim
  - event: 'Control change'
    data: '^controller 3, value (\d+)$'
    down:
      key: 'ctrl+y' # previous line
    up:
      key: 'ctrl+e' # next line
  - event: 'Control change'
    data: '^controller 9, value (\d+)$'
    down:
      text: '{' # previous paragraph
    up:
      text: '}' # next paragraph

    # bank B controllers - Firefox
  - event: 'Control change'
    data: '^controller 16, value (\d+)$'
    down:
      key: 'ctrl+Page_Up' # previous tab
    up:
      key: 'ctrl+Page_Down' # next tab

    # bank C controllers - ?
  - event: 'Control change'
    data: '^controller 22, value (\d+)$'
    down:
      key: 'ctrl+plus' # zoom in
    up:
      key: 'ctrl+minus' # zoom out
