debug: 0
device: 'MPK249'
triggers:
  - event: 'Note on'
    channel: 0
    data: 'note 36, velocity [1-9][0-9]+?'
    text: '$' 
  - event: 'Note on'
    channel: 0
    data: 'note 59, velocity [1-9][0-9]+?'
    text: 'Hello there' 
  - event: 'Note on'
    channel: 0
    data: 'note 60, velocity [1-9][0-9]+?'
    text: 'Abc 123! Xyz 667?' 
  - event: 'Note on'
    channel: 9
    data: 'note 48, velocity [1-9][0-9]+?'
    text: 'Goodbye cruel world...' 
  - event: 'Control change'
    data: 'controller 28, value 127'
    key: 'ctrl+w' 
